name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'delete-image/test'
          package-type: 'container'
          ignore-versions:  '^(0|[1-9]\d*)\.0\.0$'
          min-versions-to-keep: 1